#!/bin/bash
RESULT_PAGE="http://ordnet.dk/ddo/ordbog?query=$1"
SUGGESTION_PAGE="http://ordnet.dk/ws/ddo/livesearch?text=$1"
ARTICLES=`curl -Ls $RESULT_PAGE | grep 'tekstmedium allow' | head -2 | tail -1 | grep -oh ">[^,]*," | grep -oh "e[nt]"`
RESULT=`echo $ARTICLES | cut -c "2"`

if [ "$RESULT" = "t" ]; then
    echo "et"
elif [ "$RESULT" = "n" ]; then
    echo "en"
else
    #TODO: Add a support of different dictionaries.
    echo "Word not found or it is not a noun. Check spelling and try again."
    SUGGESTIONS=`curl -Ls $SUGGESTION_PAGE | sed -E 's/<\/li>|<li>/\'$'\n/g' | grep -v '<\|^$' | sed -e 's/^/    /'`
    if [ "$SUGGESTIONS" != "" ]; then
        echo "Did you mean one of these?"
        echo "$SUGGESTIONS"
    fi
fi
